"""Which skills can be proven, and which a posting asks for but nothing backs.

The figure guard re-derives numbers after they are written. This is the same
idea for the skill list, and it runs one step earlier: it decides which tags may
be written at all.

Two files, and the split is the point:

  skills.json  committed. The soft skills, which have no repository artifact by
               nature, plus probe overrides and the skills worth watching for
               in postings. Small, because everything derivable is derived.
  gaps.json    gitignored. Generated by `cv gaps --refresh`. For every skill in
               the portfolio, which repositories carry authored evidence and
               which postings ask for it. It names proprietary repositories,
               which is why it is not committed.

A gap is a skill a posting asks for that no repository proves. That list is the
backlog of projects worth building. A skill a CV claims without evidence is
reported separately and is the sharper defect: it is already out.
"""

from __future__ import annotations

import json
import re
import unicodedata
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import typer

import evidence

ROOT = Path(__file__).resolve().parent
COMPANIES = ROOT / "companies"
CONFIG_FILE = ROOT / "skills.json"
GAPS_FILE = ROOT / "gaps.json"
GENERAL_CVS = ("cv.json", "cv-pt.json")

# Only source counts as usage. A dependency declared in a manifest, an object
# storage option discussed in a spec, or a research doc citing a pricing page are
# not evidence that the operator built with it, and treating them as evidence is
# how an unproven "AWS" claim survived the first version of this gate.
USAGE_EXTS = (".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".py", ".go", ".rs",
              ".tf", ".sql", ".yml", ".yaml", ".sh", ".rb", ".java", ".kt")
# This repository defines the probes, so its own files match every one of them.
SELF_REPOS = {"cv", "jskills"}

_PUNCT = re.compile(r"[()\[\],;:!?\"'./]")


def load_config(path: Optional[Path] = None) -> dict:
    path = path or CONFIG_FILE
    if not path.is_file():
        return {}
    try:
        return json.loads(path.read_text())
    except ValueError:
        return {}


def load_gaps(path: Optional[Path] = None) -> dict:
    path = path or GAPS_FILE
    if not path.is_file():
        return {}
    try:
        return json.loads(path.read_text())
    except ValueError:
        return {}


def normalize(value: str) -> str:
    """Lowercase, drop accents, strip punctuation and parentheticals.

    Tags are free text and were written across years: "JavaScript moderno
    (ES6+)" and "JavaScript (ES6+)" name one skill. The accents matter because
    half the CVs are Portuguese, so "Observabilidade" must match
    "observabilidade".
    """
    text = unicodedata.normalize("NFKD", str(value or ""))
    text = "".join(c for c in text if not unicodedata.combining(c))
    text = re.sub(r"\([^)]*\)", " ", text)
    text = _PUNCT.sub(" ", text)
    return re.sub(r"\s+", " ", text).strip().lower()


def soft_set(config: Optional[dict] = None) -> set[str]:
    config = config if config is not None else load_config()
    return {normalize(s) for s in config.get("soft", [])}


def allowed_map(config: Optional[dict] = None) -> dict[str, str]:
    config = config if config is not None else load_config()
    return {normalize(k): v for k, v in config.get("allowed", {}).items()}


# ---- the portfolio ----------------------------------------

def cv_paths() -> list[Path]:
    found = sorted(COMPANIES.rglob("cv-*.json")) if COMPANIES.is_dir() else []
    found += [ROOT / n for n in GENERAL_CVS if (ROOT / n).exists()]
    return [p for p in found if "backup" not in p.name]


def claimed_tags() -> dict[str, set[str]]:
    """Skill tag -> the CVs that claim it, keyed by the tag as written."""
    claimed: dict[str, set[str]] = {}
    for path in cv_paths():
        try:
            cv = json.loads(path.read_text())
        except ValueError:
            continue
        label = str(path.relative_to(ROOT))
        for group in cv.get("skills", []):
            for tag in group.get("tags", []):
                claimed.setdefault(tag, set()).add(label)
    return claimed


def jd_paths() -> list[Path]:
    return sorted(COMPANIES.rglob("description.md")) if COMPANIES.is_dir() else []


def skill_names(config: Optional[dict] = None,
                claimed: Optional[dict] = None) -> list[str]:
    """Every skill the ledger reasons about: claimed tags plus watch-list."""
    config = config if config is not None else load_config()
    claimed = claimed if claimed is not None else claimed_tags()
    names: dict[str, str] = {}
    for tag in claimed:
        names.setdefault(normalize(tag), tag)
    for skill in config.get("extra", []):
        names.setdefault(normalize(skill), skill)
    return sorted(v for v in names.values() if normalize(v))


# ---- demand and evidence ----------------------------------

def _presence(pattern: str, text: str) -> bool:
    return re.search(rf"(?<!\w){re.escape(pattern)}(?!\w)", text) is not None


def demand(names: list[str], jds: Optional[list[Path]] = None) -> dict[str, set[str]]:
    """Skill -> the applications whose posting asks for it."""
    jds = jds if jds is not None else jd_paths()
    corpus = {jd.parent.name: normalize(jd.read_text(errors="replace")) for jd in jds}
    wanted: dict[str, set[str]] = {}
    for name in names:
        needle = normalize(name)
        if not needle:
            continue
        hits = {company for company, text in corpus.items() if _presence(needle, text)}
        if hits:
            wanted[name] = hits
    return wanted


def probe_map(names: list[str], config: Optional[dict] = None) -> dict[str, list[str]]:
    """Skill -> needles to look for. A skill's own name unless overridden."""
    config = config if config is not None else load_config()
    overrides = {normalize(k): v for k, v in config.get("probes", {}).items()}
    probes: dict[str, list[str]] = {}
    for name in names:
        key = normalize(name)
        needles = overrides.get(key) or [key]
        probes[name] = [str(n).lower() for n in needles if str(n).strip()]
    return probes


def _is_usage_file(rel: str) -> bool:
    """Whether a file can evidence usage at all."""
    low = rel.lower()
    return low.endswith(USAGE_EXTS) and "lock" not in Path(low).name


def _matches(needle: str, text: str) -> bool:
    """Word-bounded for a bare word, substring for a code pattern.

    Without this, the needle "ecs" matches the word "specs" and "aws" matches
    "laws", which is how a short skill name acquired dozens of phantom repos.
    """
    if re.fullmatch(r"[a-z0-9]+", needle):
        return re.search(rf"(?<!\w){re.escape(needle)}(?!\w)", text) is not None
    return needle in text


def scan_evidence(names: list[str], roots=None, author: Optional[str] = None
                  ) -> dict[str, list[str]]:
    """Skill -> repository labels with authored usage in source files.

    Deliberately not evidence.scan: that command is a candidate finder for a
    human to read, and its broad match is the point there. A gate that decides
    whether a CV may be built needs the narrower question, so this walks the
    repos itself, keeps only source files, and bounds short needles by word.

    Bare-word needles go through one alternation regex per file rather than a
    check each, which is what keeps a full scan to seconds instead of minutes.
    """
    probes = probe_map(names)
    roots = evidence.resolve_roots(roots)
    author = evidence.default_author() if author is None else author

    word_map: dict[str, set[str]] = {}
    sub_map: dict[str, set[str]] = {}
    for name, needles in probes.items():
        for needle in needles:
            target = word_map if re.fullmatch(r"[a-z0-9]+", needle) else sub_map
            target.setdefault(needle, set()).add(name)
    word_re = None
    if word_map:
        word_re = re.compile(r"(?<!\w)(" + "|".join(
            re.escape(w) for w in sorted(word_map, key=len, reverse=True)) + r")(?!\w)")

    per_skill: dict[str, set[str]] = {}
    for repo in evidence.find_repos(roots):
        if repo.name in SELF_REPOS:
            continue
        label = evidence.repo_label(repo, roots)
        for rel in evidence.authored_files(repo, evidence.SUFFIXES, author):
            if not _is_usage_file(rel):
                continue
            path = repo / rel
            try:
                if path.stat().st_size > evidence.MAX_BYTES:
                    continue
                text = path.read_text(errors="replace").lower()
            except OSError:
                continue
            if word_re:
                for hit in set(word_re.findall(text)):
                    for name in word_map[hit]:
                        per_skill.setdefault(name, set()).add(label)
            for needle, owners in sub_map.items():
                if needle in text:
                    for name in owners:
                        per_skill.setdefault(name, set()).add(label)
    return {name: sorted(repos) for name, repos in per_skill.items() if repos}


# ---- the ledger -------------------------------------------

def build(names: Optional[list[str]] = None, roots=None,
          author: Optional[str] = None) -> dict:
    config = load_config()
    claimed = claimed_tags()
    names = names if names is not None else skill_names(config, claimed)
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "skills": names,
        "evidence": scan_evidence(names, roots, author),
        "demand": {k: sorted(v) for k, v in demand(names).items()},
        "soft": sorted(soft_set(config)),
        "allowed": allowed_map(config),
    }


def classify(ledger: dict, config: Optional[dict] = None) -> dict:
    """Split the portfolio into evidenced, soft, allowed, and gaps."""
    config = config if config is not None else load_config()
    evidence_by_skill = ledger.get("evidence", {})
    wanted = ledger.get("demand", {})
    claimed = claimed_tags()

    soft = soft_set(config)
    allowed = allowed_map(config)

    gaps, starved, soft_hits = {}, {}, {}
    for name in ledger.get("skills", []):
        key = normalize(name)
        if key in soft:
            soft_hits[name] = sorted(wanted.get(name, []))
            continue
        if evidence_by_skill.get(name):
            continue
        if key in allowed:
            continue
        in_cvs = sorted(claimed.get(name, []))
        if wanted.get(name):
            gaps[name] = {"postings": wanted[name], "claimed_in": in_cvs}
        if in_cvs:
            starved[name] = in_cvs
    return {"gaps": gaps, "starved": starved, "soft": soft_hits}


def unproven_in(cv: dict, ledger: dict, config: Optional[dict] = None) -> list[str]:
    """Tags a single CV claims that are neither soft, allowed, nor evidenced."""
    config = config if config is not None else load_config()
    evidence_by_skill = {normalize(k): v
                         for k, v in ledger.get("evidence", {}).items()}
    soft = soft_set(config)
    allowed = allowed_map(config)
    problems = []
    for group in cv.get("skills", []):
        for tag in group.get("tags", []):
            key = normalize(tag)
            if not key or key in soft or key in allowed:
                continue
            if evidence_by_skill.get(key) or evidence_by_skill.get(normalize(tag)):
                continue
            problems.append(tag)
    return problems


def check(config: Optional[dict] = None, ledger: Optional[dict] = None
          ) -> list[dict]:
    """The gate: a tag may be soft, allowed, or evidenced. Nothing else."""
    config = config if config is not None else load_config()
    ledger = ledger if ledger is not None else load_gaps()
    if not ledger:
        return [{"problem": "no gaps.json; run `cv gaps --refresh` first"}]

    results = []
    for path in cv_paths():
        try:
            cv = json.loads(path.read_text())
        except ValueError:
            continue
        problems = unproven_in(cv, ledger, config)
        results.append({
            "path": str(path.relative_to(ROOT)),
            "problems": problems,
            "ok": not problems,
        })
    return results


# ---- commands ---------------------------------------------

app = typer.Typer(help="Skills a posting asks for that no repository proves.")


def _render(ledger: dict, config: dict, show_soft: bool) -> None:
    parts = classify(ledger, config)
    claimed = claimed_tags()
    names = ledger.get("skills", [])
    print(f"{len(names)} skills | {len(ledger.get('demand', {}))} asked for by a posting "
          f"| {len(ledger.get('evidence', {}))} with evidence\n")

    gaps = parts["gaps"]
    print(f"gaps: a posting asks, no evidence ({len(gaps)})")
    if gaps:
        for name, info in sorted(gaps.items(),
                                 key=lambda kv: (-len(kv[1]["postings"]), kv[0])):
            posts = ", ".join(info["postings"])[:58]
            print(f"  {name:28} {len(info['postings']):>2} posting(s)  {posts}")
    else:
        print("  none")

    starved = parts["starved"]
    print(f"\nclaimed in a CV, no evidence ({len(starved)})")
    if starved:
        for name, paths in sorted(starved.items()):
            print(f"  {name:28} {', '.join(paths)[:58]}")
    else:
        print("  none")

    evidenced = {normalize(k) for k in ledger.get("evidence", {})}
    wanted_keys = {normalize(k) for k in ledger.get("demand", {})}
    soft_keys = soft_set(config)
    allowed_keys = set(allowed_map(config))
    unused = sorted(t for t in claimed
                    if normalize(t) not in evidenced
                    and normalize(t) not in wanted_keys
                    and normalize(t) not in soft_keys
                    and normalize(t) not in allowed_keys)
    print(f"\nno posting asks and nothing proves ({len(unused)})")
    for tag in unused[:20]:
        print(f"  {tag}")
    if len(unused) > 20:
        print(f"  ... and {len(unused) - 20} more")

    if show_soft:
        print(f"\nsoft, never evidenced by design ({len(parts['soft'])})")
        for name in sorted(parts["soft"]):
            print(f"  {name}")


@app.callback(invoke_without_command=True)
def _default(ctx: typer.Context,
             show_soft: bool = typer.Option(False, "--soft",
                                            help="also list the soft skills")) -> None:
    if ctx.invoked_subcommand is None:
        ledger = load_gaps()
        if not ledger:
            typer.echo("no gaps.json yet; run `cv gaps --refresh` first", err=True)
            raise typer.Exit(code=1)
        _render(ledger, load_config(), show_soft)


@app.command("refresh")
def gaps_refresh(
    root: Optional[list[str]] = typer.Option(None, "--root", help="repeatable"),
    author: Optional[str] = typer.Option(None, "--author"),
) -> None:
    """Scan the repositories and rewrite the gitignored gaps.json."""
    ledger = build(roots=root, author=author)
    GAPS_FILE.write_text(json.dumps(ledger, ensure_ascii=False, indent=2) + "\n")
    typer.echo(f"wrote {GAPS_FILE.name}: {len(ledger['skills'])} skills, "
               f"{len(ledger['evidence'])} with evidence, "
               f"{len(ledger['demand'])} asked for by a posting")


@app.command("check")
def gaps_check() -> None:
    """Fail a CV that claims a skill no repository proves."""
    ledger = load_gaps()
    if not ledger:
        typer.echo("no gaps.json; run `cv gaps --refresh` first", err=True)
        raise typer.Exit(code=1)

    results = check(ledger=ledger)
    bad = [r for r in results if not r.get("ok", True)]
    for r in results:
        if r.get("problem"):
            typer.echo(f"  ! {r['problem']}", err=True)
            raise typer.Exit(code=2)
    for r in results:
        if r["ok"]:
            typer.echo(f"  ok    {r['path']}")
        else:
            typer.echo(f"  FAIL  {r['path']}  <- {', '.join(r['problems'])}")
    typer.echo(f"\n{len(results) - len(bad)}/{len(results)} CVs claim only proven skills.")
    if bad:
        raise typer.Exit(code=1)


if __name__ == "__main__":
    app()
