"""Which skills can be proven, and which a posting asks for but nothing backs.

The figure guard re-derives numbers after they are written. This is the same
idea for the skill list, and it runs one step earlier: it decides which tags may
be written at all.

Two files, and the split is the point:

  skills.json  committed. The soft skills, which have no repository artifact by
               nature, plus probe overrides and the skills worth watching for
               in postings. Small, because everything derivable is derived.
  gaps.json    gitignored. Generated by `cv gaps --refresh`. For every skill in
               the portfolio, which repositories carry authored evidence and
               which postings ask for it. It names proprietary repositories,
               which is why it is not committed.

A gap is a skill a posting asks for that no repository proves. That list is the
backlog of projects worth building. A skill a CV claims without evidence is
reported separately and is the sharper defect: it is already out.
"""

from __future__ import annotations

import json
import re
import unicodedata
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import typer

import evidence

ROOT = Path(__file__).resolve().parent
COMPANIES = ROOT / "companies"
CONFIG_FILE = ROOT / "skills.json"
GAPS_FILE = ROOT / "gaps.json"
# Unmapped packages the discovery pass found in authored source, waiting for
# the operator to approve (spec 0009). Gitignored like gaps.json: it reports
# what an employer's repository imports.
CANDIDATES_FILE = ROOT / "candidates.json"
# Operator confirmations: a demanded skill the scan could not place, affirmed
# by hand with the engagement that used it (ADR 0007). Gitignored for the same
# reason: the engagement names past employers.
CONFIRMATIONS_FILE = ROOT / "confirmations.json"
GENERAL_CVS = ("cv.json", "cv-pt.json")

# Only source counts as usage. A dependency declared in a manifest, an object
# storage option discussed in a spec, or a research doc citing a pricing page are
# not evidence that the operator built with it, and treating them as evidence is
# how an unproven "AWS" claim survived the first version of this gate.
USAGE_EXTS = (".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".py", ".go", ".rs",
              ".tf", ".sql", ".yml", ".yaml", ".sh", ".rb", ".java", ".kt")
# This repository defines the probes, so its own files match every one of them.
SELF_REPOS = {"cv", "jskills"}

_PUNCT = re.compile(r"[()\[\],;:!?\"'./]")


def load_config(path: Optional[Path] = None) -> dict:
    path = path or CONFIG_FILE
    if not path.is_file():
        return {}
    try:
        return json.loads(path.read_text())
    except ValueError:
        return {}


def load_gaps(path: Optional[Path] = None) -> dict:
    path = path or GAPS_FILE
    if not path.is_file():
        return {}
    try:
        return json.loads(path.read_text())
    except ValueError:
        return {}


def normalize(value: str) -> str:
    """Lowercase, drop accents, strip punctuation and parentheticals.

    Tags are free text and were written across years: "JavaScript moderno
    (ES6+)" and "JavaScript (ES6+)" name one skill. The accents matter because
    half the CVs are Portuguese, so "Observabilidade" must match
    "observabilidade".
    """
    text = unicodedata.normalize("NFKD", str(value or ""))
    text = "".join(c for c in text if not unicodedata.combining(c))
    text = re.sub(r"\([^)]*\)", " ", text)
    text = _PUNCT.sub(" ", text)
    return re.sub(r"\s+", " ", text).strip().lower()


def soft_set(config: Optional[dict] = None) -> set[str]:
    config = config if config is not None else load_config()
    return {normalize(s) for s in config.get("soft", [])}


def allowed_map(config: Optional[dict] = None) -> dict[str, str]:
    config = config if config is not None else load_config()
    return {normalize(k): v for k, v in config.get("allowed", {}).items()}


# ---- the portfolio ----------------------------------------

def cv_paths() -> list[Path]:
    found = sorted(COMPANIES.rglob("cv-*.json")) if COMPANIES.is_dir() else []
    found += [ROOT / n for n in GENERAL_CVS if (ROOT / n).exists()]
    return [p for p in found if "backup" not in p.name]


def claimed_tags() -> dict[str, set[str]]:
    """Skill tag -> the CVs that claim it, keyed by the tag as written."""
    claimed: dict[str, set[str]] = {}
    for path in cv_paths():
        try:
            cv = json.loads(path.read_text())
        except ValueError:
            continue
        label = str(path.relative_to(ROOT))
        for group in cv.get("skills", []):
            for tag in group.get("tags", []):
                claimed.setdefault(tag, set()).add(label)
    return claimed


def jd_paths() -> list[Path]:
    return sorted(COMPANIES.rglob("description.md")) if COMPANIES.is_dir() else []


def skill_names(config: Optional[dict] = None,
                claimed: Optional[dict] = None) -> list[str]:
    """Every skill the ledger reasons about: claimed tags plus watch-list."""
    config = config if config is not None else load_config()
    claimed = claimed if claimed is not None else claimed_tags()
    names: dict[str, str] = {}
    for tag in claimed:
        names.setdefault(normalize(tag), tag)
    for skill in config.get("extra", []):
        names.setdefault(normalize(skill), skill)
    return sorted(v for v in names.values() if normalize(v))


# ---- demand and evidence ----------------------------------

def _presence(pattern: str, text: str) -> bool:
    return re.search(rf"(?<!\w){re.escape(pattern)}(?!\w)", text) is not None


def demand(names: list[str], jds: Optional[list[Path]] = None) -> dict[str, set[str]]:
    """Skill -> the applications whose posting asks for it."""
    jds = jds if jds is not None else jd_paths()
    corpus = {jd.parent.name: normalize(jd.read_text(errors="replace")) for jd in jds}
    wanted: dict[str, set[str]] = {}
    for name in names:
        needle = normalize(name)
        if not needle:
            continue
        hits = {company for company, text in corpus.items() if _presence(needle, text)}
        if hits:
            wanted[name] = hits
    return wanted


def probe_map(names: list[str], config: Optional[dict] = None) -> dict[str, list[str]]:
    """Skill -> needles to look for. A skill's own name unless overridden."""
    config = config if config is not None else load_config()
    overrides = {normalize(k): v for k, v in config.get("probes", {}).items()}
    probes: dict[str, list[str]] = {}
    for name in names:
        key = normalize(name)
        needles = overrides.get(key) or [key]
        probes[name] = [str(n).lower() for n in needles if str(n).strip()]
    return probes


def _is_usage_file(rel: str) -> bool:
    """Whether a file can evidence usage at all."""
    low = rel.lower()
    return low.endswith(USAGE_EXTS) and "lock" not in Path(low).name


def _matches(needle: str, text: str) -> bool:
    """Word-bounded for a bare word, substring for a code pattern.

    Without this, the needle "ecs" matches the word "specs" and "aws" matches
    "laws", which is how a short skill name acquired dozens of phantom repos.
    """
    if re.fullmatch(r"[a-z0-9]+", needle):
        return re.search(rf"(?<!\w){re.escape(needle)}(?!\w)", text) is not None
    return needle in text


def scan_evidence(names: list[str], roots=None, author: Optional[str] = None,
                  additions: Optional[dict] = None) -> dict[str, list[str]]:
    """Skill -> repositories whose authored diffs use the skill.

    Deliberately not evidence.scan: that command is a candidate finder for a
    human to read, and its broad match is the point there. A gate that decides
    whether a CV may be built asks the narrower question and matches the lines
    the operator's commits added, never a file they merely touched (ADR 0008).
    """
    probes = probe_map(names)
    if additions is None:
        additions = _collect_additions(roots, author)

    word_map: dict[str, set[str]] = {}
    sub_map: dict[str, set[str]] = {}
    for name, needles in probes.items():
        for needle in needles:
            target = word_map if re.fullmatch(r"[a-z0-9]+", needle) else sub_map
            target.setdefault(needle, set()).add(name)
    word_re = None
    if word_map:
        word_re = re.compile(r"(?<!\w)(" + "|".join(
            re.escape(w) for w in sorted(word_map, key=len, reverse=True)) + r")(?!\w)")

    per_skill: dict[str, set[str]] = {}
    for label, corpus in additions.items():
        text = corpus.lower()
        if word_re:
            for hit in set(word_re.findall(text)):
                for name in word_map[hit]:
                    per_skill.setdefault(name, set()).add(label)
        for needle, owners in sub_map.items():
            if needle in text:
                for name in owners:
                    per_skill.setdefault(name, set()).add(label)
    return {name: sorted(repos) for name, repos in per_skill.items() if repos}


# ---- discovery: packages imported by authored source ----------------------

# A dependency named in source is a stronger signal than one named in a probe:
# it is the actual import line, not a word that might appear in prose. The
# mapping in skills.json binds packages to skills, and this pass collects the
# packages and resolves them. Node core and Python stdlib modules appear in
# every file and carry no signal, so they are excluded from candidates.
BUILTINS = {"assert", "async_hooks", "buffer", "child_process", "cluster",
            "console", "constants", "crypto", "dgram", "diagnostics_channel",
            "dns", "domain", "events", "fs", "http", "http2", "https",
            "inspector", "module", "net", "os", "path", "perf_hooks",
            "process", "punycode", "querystring", "readline", "repl", "stream",
            "string_decoder", "timers", "tls", "trace_events", "tty", "url",
            "util", "v8", "vm", "wasi", "worker_threads", "zlib", "test"}

PY_STDLIB = {"os", "sys", "json", "re", "time", "datetime", "math", "random",
             "string", "logging", "pathlib", "collections", "functools",
             "itertools", "subprocess", "typing", "abc", "asyncio", "copy",
             "argparse", "hashlib", "uuid", "socket", "threading", "queue",
             "dataclasses", "enum", "io", "glob", "shutil", "statistics",
             "tempfile", "textwrap", "traceback", "unittest", "urllib",
             "warnings", "weakref", "contextlib", "base64", "bisect", "calendar",
             "cmath", "csv", "decimal", "difflib", "dis", "email", "fileinput",
             "fnmatch", "getpass", "gettext", "gc", "gzip", "heapq", "hmac",
             "html", "http", "importlib", "inspect", "keyword", "linecache",
             "locale", "marshal", "mimetypes", "numbers", "operator", "optparse",
             "pickle", "pkgutil", "platform", "pprint", "profile", "pstats",
             "pydoc", "quopri", "reprlib", "select", "selectors", "signal",
             "site", "smtplib", "socketserver", "sqlite3", "ssl", "struct",
             "tabnanny", "tarfile", "telnetlib", "test", "timeit", "tokenize",
             "tomllib", "turtle", "types", "unicodedata", "xml", "zipfile",
             "zoneinfo", "secrets", "stringprep"}

_JS_IMPORT_RE = re.compile(
    r"""
    \bimport\b[^;"']*?\bfrom\s*['"]([^'"]+)['"]
    | \bimport\s*['"]([^'"]+)['"]
    | \bexport\b[^;"']*?\bfrom\s*['"]([^'"]+)['"]
    | \brequire\s*\(\s*['"]([^'"]+)['"]\s*\)
    | \bimport\s*\(\s*['"]([^'"]+)['"]\s*\)
    """, re.VERBOSE)
_PY_IMPORT_RE = re.compile(r"^\s*(?:from|import)\s+([A-Za-z_][A-Za-z0-9_.]*)",
                           re.MULTILINE)
_GO_IMPORT_RE = re.compile(r'^\s*import\s+(?:[A-Za-z_]\w*\s+)?["]([^"\n]+)["]')
_RB_IMPORT_RE = re.compile(r"\brequire\s*['\"]([^'\"]+)['\"]")


def _pkg_base(pkg: str) -> str:
    """A module specifier reduced to its importable package.

    `@scope/name/path` keeps its scope, `name/path` keeps its leading segment,
    and relative or builtin modules mean nothing to an employer.
    """
    pkg = pkg.strip().strip("'\"")
    if not pkg or pkg.startswith("."):
        return ""
    if pkg.startswith("@/"):
        return ""  # a TypeScript path alias to src/, never a package
    if pkg.startswith("@"):
        parts = pkg.split("/")
        base = "/".join(parts[:2]) if len(parts) >= 2 else pkg
    else:
        base = pkg.split("/")[0]
    base = base.lower()
    if base.startswith("node:"):
        base = base.split(":", 1)[1]
    return "" if base in BUILTINS or base in PY_STDLIB else base


def _packages_line(text: str, low: str) -> set[str]:
    if low.endswith((".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs")):
        out: set[str] = set()
        for groups in _JS_IMPORT_RE.findall(text):
            for pkg in groups:
                base = _pkg_base(pkg)
                if base:
                    out.add(base)
        return out
    if low.endswith(".py"):
        out = set()
        for match in _PY_IMPORT_RE.finditer(text):
            base = match.group(1).split(".")[0].lower()
            if base:
                out.add(base)
        return out
    if low.endswith(".go"):
        return {m.lower() for m in _GO_IMPORT_RE.findall(text) if m}
    if low.endswith(".rb"):
        return {base for m in _RB_IMPORT_RE.findall(text)
                if (base := _pkg_base(m))}
    return set()


def _packages_text(text: str) -> set[str]:
    """Imports across languages, for a diff corpus that mixes them."""
    pkgs: set[str] = set()
    for groups in _JS_IMPORT_RE.findall(text):
        for pkg in groups:
            base = _pkg_base(pkg)
            if base:
                pkgs.add(base)
    for match in _PY_IMPORT_RE.finditer(text):
        base = match.group(1).split(".")[0].lower()
        if base:
            pkgs.add(base)
    pkgs.update(m.lower() for m in _GO_IMPORT_RE.findall(text) if m)
    for m in _RB_IMPORT_RE.findall(text):
        base = _pkg_base(m)
        if base:
            pkgs.add(base)
    return pkgs


def _collect_additions(roots=None, author: Optional[str] = None
                       ) -> dict[str, str]:
    """Repo label -> the lines the author's commits added.

    One diff read shared by the probe scan and the import scan, so refresh
    does not pay the git log -p cost twice (ADR 0008).
    """
    config = load_config()
    if roots is None:
        roots = config.get("roots") or None
    roots = evidence.resolve_roots(roots)
    if author is None:
        authors = config.get("authors") or []
        author = ("\\|".join(authors) if authors
                  else evidence.default_author())
    out: dict[str, str] = {}
    usage_globs = tuple(f"*{ext}" for ext in USAGE_EXTS)
    for repo in evidence.find_repos(roots):
        if repo.name in SELF_REPOS:
            continue
        corpus = evidence.authored_additions(repo, author, usage_globs)
        if corpus:
            out[evidence.repo_label(repo, roots)] = corpus
    return out


def scan_packages(roots=None, author: Optional[str] = None,
                  additions: Optional[dict] = None
                  ) -> dict[str, list[str]]:
    """Repo label -> packages its authored diff lines import.

    Shares the diff walk with scan_evidence, so employer repositories under
    every configured root count the same as ~/lab (spec 0009).
    """
    if additions is None:
        additions = _collect_additions(roots, author)
    return {label: sorted(_packages_text(corpus))
            for label, corpus in sorted(additions.items())
            if _packages_text(corpus)}


def import_evidence(config: Optional[dict] = None, roots=None,
                    author: Optional[str] = None,
                    per_repo: Optional[dict] = None,
                    additions: Optional[dict] = None
                    ) -> dict[str, list[str]]:
    """Skill -> repos whose authored diff imports one of its packages.

    The mapping in skills.json is the reviewable artifact: a package binds its
    skill, and nothing becomes a skill without a mapping or an approval.
    """
    config = config if config is not None else load_config()
    if per_repo is None:
        per_repo = scan_packages(roots, author, additions)
    pkg_to_skill: dict[str, str] = {}
    for skill, pkgs in config.get("mapping", {}).items():
        for pkg in pkgs:
            base = _pkg_base(pkg)
            if base:
                pkg_to_skill.setdefault(base, skill)
    mapped: dict[str, set[str]] = {}
    for label, pkgs in per_repo.items():
        for pkg in pkgs:
            skill = pkg_to_skill.get(pkg)
            if skill:
                mapped.setdefault(skill, set()).add(label)
    return {skill: sorted(labels) for skill, labels in mapped.items() if labels}


# ---- the ledger -------------------------------------------

def build(names: Optional[list[str]] = None, roots=None,
          author: Optional[str] = None) -> dict:
    config = load_config()
    claimed = claimed_tags()
    names = names if names is not None else skill_names(config, claimed)
    additions = _collect_additions(roots, author)
    evidence_map = scan_evidence(names, roots, author, additions)
    for skill, repos in import_evidence(config, roots, author,
                                        additions=additions).items():
        evidence_map.setdefault(skill, set())
        combined = set(evidence_map[skill])
        combined.update(repos)
        evidence_map[skill] = sorted(combined)
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "skills": names,
        "evidence": evidence_map,
        "demand": {k: sorted(v) for k, v in demand(names).items()},
        "soft": sorted(soft_set(config)),
        "allowed": allowed_map(config),
    }


def load_confirmations(path: Optional[Path] = None) -> dict:
    path = path or CONFIRMATIONS_FILE
    if not path.is_file():
        return {}
    try:
        return json.loads(path.read_text())
    except ValueError:
        return {}


def save_confirmations(data: dict, path: Optional[Path] = None) -> None:
    path = path or CONFIRMATIONS_FILE
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")


def classify(ledger: dict, config: Optional[dict] = None,
             confirmations: Optional[dict] = None) -> dict:
    """Split the portfolio into evidenced, soft, allowed, confirmed, and gaps.

    Gaps follow ADR 0007: a posting asks for a skill, the code does not prove
    it, and the operator was asked and could not place it. A skill the operator
    has not been asked about yet lands in needs_answer, which is the report
    doing the asking.
    """
    config = config if config is not None else load_config()
    confirmations = confirmations if confirmations is not None \
        else load_confirmations()
    conf_norm = {normalize(k): v for k, v in confirmations.items()}
    evidence_by_skill = ledger.get("evidence", {})
    wanted = ledger.get("demand", {})
    claimed = claimed_tags()

    soft = soft_set(config)
    allowed = allowed_map(config)

    gaps, starved, soft_hits, needs_answer, confirmed = {}, {}, {}, {}, {}
    for name in ledger.get("skills", []):
        key = normalize(name)
        if key in soft:
            soft_hits[name] = sorted(wanted.get(name, []))
            continue
        if evidence_by_skill.get(name):
            continue
        if key in allowed:
            continue
        in_cvs = sorted(claimed.get(name, []))
        conf = conf_norm.get(key)
        if wanted.get(name):
            if conf is not None and conf.get("engagement"):
                confirmed[name] = {"engagement": conf["engagement"],
                                   "postings": sorted(wanted[name])}
            elif conf is not None:
                gaps[name] = {"postings": wanted[name], "claimed_in": in_cvs}
            else:
                needs_answer[name] = sorted(wanted[name])
        elif in_cvs:
            if conf is not None and conf.get("engagement"):
                confirmed[name] = {"engagement": conf["engagement"],
                                   "postings": []}
            else:
                starved[name] = in_cvs
    return {"gaps": gaps, "needs_answer": needs_answer,
            "confirmed": confirmed, "starved": starved, "soft": soft_hits}


def unproven_in(cv: dict, ledger: dict, config: Optional[dict] = None,
                confirmations: Optional[dict] = None) -> list[str]:
    """Tags a single CV claims that are neither soft, allowed, confirmed, nor evidenced."""
    config = config if config is not None else load_config()
    confirmations = confirmations if confirmations is not None \
        else load_confirmations()
    conf_norm = {normalize(k): v for k, v in confirmations.items()}
    evidence_by_skill = {normalize(k): v
                         for k, v in ledger.get("evidence", {}).items()}
    soft = soft_set(config)
    allowed = allowed_map(config)
    problems = []
    for group in cv.get("skills", []):
        for tag in group.get("tags", []):
            key = normalize(tag)
            if not key or key in soft or key in allowed:
                continue
            conf = conf_norm.get(key)
            if conf is not None and conf.get("engagement"):
                continue
            if evidence_by_skill.get(key) or evidence_by_skill.get(normalize(tag)):
                continue
            problems.append(tag)
    return problems


def check(config: Optional[dict] = None, ledger: Optional[dict] = None
          ) -> list[dict]:
    """The gate: a tag may be soft, allowed, or evidenced. Nothing else."""
    config = config if config is not None else load_config()
    ledger = ledger if ledger is not None else load_gaps()
    if not ledger:
        return [{"problem": "no gaps.json; run `cv gaps --refresh` first"}]

    results = []
    for path in cv_paths():
        try:
            cv = json.loads(path.read_text())
        except ValueError:
            continue
        problems = unproven_in(cv, ledger, config)
        results.append({
            "path": str(path.relative_to(ROOT)),
            "problems": problems,
            "ok": not problems,
        })
    return results


# ---- commands ---------------------------------------------

app = typer.Typer(help="Skills a posting asks for that no repository proves.")


def _render(ledger: dict, config: dict, show_soft: bool) -> None:
    parts = classify(ledger, config)
    claimed = claimed_tags()
    names = ledger.get("skills", [])
    confirmed = parts["confirmed"]
    print(f"{len(names)} skills | {len(ledger.get('demand', {}))} asked for by a posting "
          f"| {len(ledger.get('evidence', {}))} with evidence "
          f"| {len(confirmed)} affirmed by you\n")

    needs_answer = parts["needs_answer"]
    print(f"ask the operator (a posting asks, nothing proves yet) "
          f"({len(needs_answer)})")
    if needs_answer:
        for name, postings in sorted(needs_answer.items(),
                                     key=lambda kv: (-len(kv[1]), kv[0])):
            posts = ", ".join(postings)[:40]
            print(f"  {name:28} {len(postings):>2} posting(s)  {posts}")
            print(f"      cv gaps answer --skill {name!r} "
                  f"--engagement ENGAGEMENT | --could-not-place")
    else:
        print("  none")

    if confirmed:
        print(f"\naffirmed by you, with the engagement ({len(confirmed)})")
        for name, info in sorted(confirmed.items()):
            posts = f", {len(info['postings'])} posting(s)" if info["postings"] else ""
            print(f"  {name:28} {info['engagement']}{posts}")

    gaps = parts["gaps"]
    print(f"\ngaps (a posting asks, you could not place it) ({len(gaps)})")
    if gaps:
        for name, info in sorted(gaps.items(),
                                 key=lambda kv: (-len(kv[1]["postings"]), kv[0])):
            posts = ", ".join(info["postings"])[:58]
            print(f"  {name:28} {len(info['postings']):>2} posting(s)  {posts}")
    else:
        print("  none")

    starved = parts["starved"]
    print(f"\nclaimed in a CV, no evidence ({len(starved)})")
    if starved:
        for name, paths in sorted(starved.items()):
            print(f"  {name:28} {', '.join(paths)[:58]}")
    else:
        print("  none")

    evidenced = {normalize(k) for k in ledger.get("evidence", {})}
    wanted_keys = {normalize(k) for k in ledger.get("demand", {})}
    soft_keys = soft_set(config)
    allowed_keys = set(allowed_map(config))
    unused = sorted(t for t in claimed
                    if normalize(t) not in evidenced
                    and normalize(t) not in wanted_keys
                    and normalize(t) not in soft_keys
                    and normalize(t) not in allowed_keys)
    print(f"\nno posting asks and nothing proves ({len(unused)})")
    for tag in unused[:20]:
        print(f"  {tag}")
    if len(unused) > 20:
        print(f"  ... and {len(unused) - 20} more")

    if show_soft:
        print(f"\nsoft, never evidenced by design ({len(parts['soft'])})")
        for name in sorted(parts["soft"]):
            print(f"  {name}")


@app.callback(invoke_without_command=True)
def _default(ctx: typer.Context,
             show_soft: bool = typer.Option(False, "--soft",
                                            help="also list the soft skills")) -> None:
    if ctx.invoked_subcommand is None:
        ledger = load_gaps()
        if not ledger:
            typer.echo("no gaps.json yet; run `cv gaps --refresh` first", err=True)
            raise typer.Exit(code=1)
        _render(ledger, load_config(), show_soft)


@app.command("refresh")
def gaps_refresh(
    root: Optional[list[str]] = typer.Option(None, "--root", help="repeatable"),
    author: Optional[str] = typer.Option(None, "--author"),
) -> None:
    """Scan the repositories and rewrite the gitignored gaps.json."""
    ledger = build(roots=root, author=author)
    GAPS_FILE.write_text(json.dumps(ledger, ensure_ascii=False, indent=2) + "\n")
    typer.echo(f"wrote {GAPS_FILE.name}: {len(ledger['skills'])} skills, "
               f"{len(ledger['evidence'])} with evidence, "
               f"{len(ledger['demand'])} asked for by a posting")


@app.command("check")
def gaps_check() -> None:
    """Fail a CV that claims a skill no repository proves."""
    ledger = load_gaps()
    if not ledger:
        typer.echo("no gaps.json; run `cv gaps --refresh` first", err=True)
        raise typer.Exit(code=1)

    results = check(ledger=ledger)
    bad = [r for r in results if not r.get("ok", True)]
    for r in results:
        if r.get("problem"):
            typer.echo(f"  ! {r['problem']}", err=True)
            raise typer.Exit(code=2)
    for r in results:
        if r["ok"]:
            typer.echo(f"  ok    {r['path']}")
        else:
            typer.echo(f"  FAIL  {r['path']}  <- {', '.join(r['problems'])}")
    typer.echo(f"\n{len(results) - len(bad)}/{len(results)} CVs claim only proven skills.")
    if bad:
        raise typer.Exit(code=1)


@app.command("answer")
def gaps_answer(
    skill: str = typer.Argument(..., help="the skill name, as the report wrote it"),
    engagement: Optional[str] = typer.Option(None, "--engagement", "-e",
                                             help="past engagement that used it"),
    could_not_place: bool = typer.Option(False, "--could-not-place",
                                         help="asked and could not place it anywhere"),
    note: Optional[str] = typer.Option(None, "--note"),
) -> None:
    """Record the operator's answer for a demanded, unevidenced skill.

    An engagement moves the skill out of the gaps. --could-not-place keeps it
    there, which is the honest end state when no employer ever used it.
    """
    if engagement and could_not_place:
        typer.echo("give --engagement OR --could-not-place, not both", err=True)
        raise typer.Exit(code=2)
    if not engagement and not could_not_place:
        typer.echo("give --engagement ENGAGEMENT or --could-not-place", err=True)
        raise typer.Exit(code=2)

    confirmation = {"engagement": None if could_not_place else engagement,
                    "note": note,
                    "when": datetime.now(timezone.utc).isoformat(timespec="seconds")}
    saved = load_confirmations()
    saved[skill] = confirmation
    save_confirmations(saved)
    if could_not_place:
        typer.echo(f"recorded: {skill} stays a gap (could not place it)")
    else:
        typer.echo(f"recorded: {skill} moves out of the gaps "
                   f"(affirmed: {engagement})")


skillscan_app = typer.Typer(
    help="Packages authored source imports, mapped to skills or listed as candidates.")


@skillscan_app.callback(invoke_without_command=True)
def skillscan(
    root: Optional[list[str]] = typer.Option(None, "--root", help="repeatable"),
    author: Optional[str] = typer.Option(None, "--author"),
) -> None:
    """Discover skills from the code the operator actually wrote (spec 0009)."""
    config = load_config()
    if root:
        roots = evidence.resolve_roots(root)
    else:
        roots = evidence.resolve_roots(config.get("roots") or None)
    if author is None:
        authors = config.get("authors") or []
        author = ("\\|".join(authors) if authors else evidence.default_author())

    per_repo = scan_packages(None if not root else root, author)
    mapping = config.get("mapping", {})
    pkg_to_skill: dict[str, str] = {}
    for skill, pkgs in mapping.items():
        for pkg in pkgs:
            base = _pkg_base(pkg)
            if base:
                pkg_to_skill.setdefault(base, skill)

    total = sum(len(pkgs) for pkgs in per_repo.values())
    typer.echo(f"{len(per_repo)} repos, {total} packages under "
               f"{', '.join(str(r) for r in roots)}")
    typer.echo(f"author filter: {author or '(none: every commit counts)'}\n")

    for label in sorted(per_repo):
        pkgs = per_repo[label]
        mapped: dict[str, list[str]] = {}
        unmapped: list[str] = []
        for pkg in pkgs:
            skill = pkg_to_skill.get(pkg)
            if skill:
                mapped.setdefault(skill, []).append(pkg)
            else:
                unmapped.append(pkg)
        typer.echo(f"{label}:")
        for skill in sorted(mapped):
            packages = ", ".join(sorted(mapped[skill]))[:86]
            typer.echo(f"    {skill:22} <- {packages}")
        if unmapped:
            shown = ", ".join(unmapped[:6])
            more = f" ... and {len(unmapped) - 6} more" if len(unmapped) > 6 else ""
            typer.echo(f"    candidate: {shown}{more}")

    used: dict[str, set[str]] = {}
    for label, pkgs in per_repo.items():
        for pkg in pkgs:
            if pkg in pkg_to_skill:
                continue
            used.setdefault(pkg, set()).add(label)
    strong = {pkg: sorted(labels) for pkg, labels in used.items()
              if len(labels) >= 2}
    ordered = sorted(strong.items(), key=lambda kv: (-len(kv[1]), kv[0]))
    CANDIDATES_FILE.write_text(json.dumps(
        {"generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
         "candidates": dict(ordered[:200])},
        ensure_ascii=False, indent=2) + "\n")

    typer.echo(f"\ncandidates in gitignored {CANDIDATES_FILE.name}: "
               f"{len(ordered[:200])} packages used in 2+ repos")
    for pkg, labels in ordered[:20]:
        typer.echo(f"    {pkg:38} {len(labels):>2} repos  {', '.join(labels[:3])}")


if __name__ == "__main__":
    app()
